


pub const ID_CONNECTED_PING: u8 = 0x00;
pub const ID_UNCONNECTED_PING: u8 = 0x01;
pub const ID_UNCONNECTED_PING_OPEN_CONNECTIONS: u8 = 0x02;
pub const ID_CONNECTED_PONG: u8 = 0x03;
pub const ID_DETECT_LOST_CONNECTIONS: u8 = 0x04;
pub const ID_OPEN_CONNECTION_REQUEST_1: u8 = 0x05;
pub const ID_OPEN_CONNECTION_REPLY_1: u8 = 0x06;
pub const ID_OPEN_CONNECTION_REQUEST_2: u8 = 0x07;
pub const ID_OPEN_CONNECTION_REPLY_2: u8 = 0x08;
pub const ID_CONNECTION_REQUEST: u8 = 0x09;
pub const ID_REMOTE_SYSTEM_REQUIRES_PUBLIC_KEY: u8 = 0x0a;
pub const ID_OUR_SYSTEM_REQUIRES_SECURITY: u8 = 0x0b;
pub const ID_PUBLIC_KEY_MISMATCH: u8 = 0x0c;
pub const ID_OUT_OF_BAND_INTERNAL: u8 = 0x0d;
pub const ID_SND_RECEIPT_ACKED: u8 = 0x0e;
pub const ID_SND_RECEIPT_LOSS: u8 = 0x0f;
pub const ID_CONNECTION_REQUEST_ACCEPTED: u8 = 0x10;
pub const ID_CONNECTION_ATTEMPT_FAILED: u8 = 0x11;
pub const ID_ALREADY_CONNECTED: u8 = 0x12;
pub const ID_NEW_INCOMING_CONNECTION: u8 = 0x13;
pub const ID_NO_FREE_INCOMING_CONNECTIONS: u8 = 0x14;
pub const ID_DISCONNECTION_NOTIFICATION: u8 = 0x15;
pub const ID_CONNECTION_LOST: u8 = 0x16;
pub const ID_CONNECTION_BANNED: u8 = 0x17;
pub const ID_INVALID_PASSWORD: u8 = 0x18;
pub const ID_INCOMPATIBLE_PROTOCOL_VERSION: u8 = 0x19;
pub const ID_IP_RECENTLY_CONNECTED: u8 = 0x1a;
pub const ID_TIMESTAMP: u8 = 0x1b;
pub const ID_UNCONNECTED_PONG: u8 = 0x1c;